### PR TITLE
Pipeline hard flush

### PR DESCRIPTION
**Pull request by kongty**
Merge pipeline hardflush to mastar

### CODE REVIEW

**Comment by Kuree** [comment]
@kongty @jack-melchert Can you break this into multiple independent PRs?

**Comment by jack-melchert** [comment]
Yeah sorry about that wasn't expecting this pull request quite yet. I can work on adding just the changes for getting the flush working to a new branch and make that pull request first.

**Comment by Kuree** [comment]
Is this PR still happening or are we going to use this branch as master from now on?

**Comment by jack-melchert** [comment]
This is a good point to do the pull request. There are a lot of changes, but I've only included things necessary to do the rescheduling of the harden flush.

**Comment by Kuree** [comment]
Can you refactor out the visualization?

**Comment by jack-melchert** [comment]
Sure, I'll create two PRs, one for visualization, one for everything else

**Pull request closed without merging**
